version: '3'
services:
  app:
    build:
      context: "../"
      dockerfile: "./local/Dockerfile"
    ports:
        - "8000:8000"
    volumes:
        - "../src:/app"
    image: "python-hello-world:latest"
    tty: "true"
    networks:
      - container-link
networks:
  container-link:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.100.0/24"
