# Python image to use.
FROM python:3.8

# Set the working directory to /app
WORKDIR /tests

# Install package for tests
RUN pip install pytest
RUN pip install coverage
RUN pip install requests
RUN pip install retrying
